#include "Robot_State_Upper.h"
#include "UpperPara.h"

void Robot_State_Upper::Set_Initialize()
{
	set_user_value();
	Upperpara_initialize();
}
void Robot_State_Upper::Set_Joint_Value(VectorXD q)
{
	_q=q;
}
void Robot_State_Upper::Get_IK_Value()
{
	Get_T_Rarm(_Rarm.T);
	Get_T_Larm(_Larm.T);

	Get_Larm_angle(_Larm.EulerAngle);
	Get_Rarm_angle(_Rarm.EulerAngle);

	Get_Rarm_Jacobian(_Rarm.J);
	Get_Larm_Jacobian(_Larm.J);

	for (int i=0; i<7; i++) {
		_Rarm.q(i) = _q(i+RA_BEGIN);
		_Larm.q(i) = _q(i+LA_BEGIN);
	}

}
void Robot_State_Upper::Get_Rarm_Jacobian(MatrixXD& J)
{
	VectorXD q = _q;

	J.resize(6,7);
	J.setZero();

	J(0,0)= l3_z*(cos(q(RA_BEGIN+3))*(sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) - cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))) + cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3))) - l3_y*(sin(q(RA_BEGIN+3))*(sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) - cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))) - cos(q(RA_BEGIN))*cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN+1))) - l4_y*(sin(q(RA_BEGIN+3))*(sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) - cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))) - cos(q(RA_BEGIN))*cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN+1))) - l5_z*(cos(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+3))*(sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) - cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))) - cos(q(RA_BEGIN))*cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN+1))) - cos(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+3))*(sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) - cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))) + cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3))) + sin(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)) + cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN+2))))) + sin(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+3))*(sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) - cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))) + cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3))) - cos(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)) + cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN+2))))) - l1_z*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)) + l1_y*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)) + l2_y*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1));
	J(0,1)= l5_z*(cos(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN)) - cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3))) + cos(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+3)) + cos(q(RA_BEGIN+2))*cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))) - sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+2))*sin(q(RA_BEGIN+4)))) - sin(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+3)) + cos(q(RA_BEGIN+2))*cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))) + cos(q(RA_BEGIN+4))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+2)))) + l3_y*(cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN)) - cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3))) + l3_z*(cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+3)) + cos(q(RA_BEGIN+2))*cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))) + l4_y*(cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN)) - cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3))) + l1_y*cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN)) + l2_y*cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN)) + l1_z*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1));
	J(0,2)= l5_z*(sin(q(RA_BEGIN+6))*(cos(q(RA_BEGIN+4))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) + cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN+4))*(cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)) - cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))) + cos(q(RA_BEGIN+6))*(cos(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+4))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) - cos(q(RA_BEGIN+3))*cos(q(RA_BEGIN+4))*(cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)) - cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))) + sin(q(RA_BEGIN+3))*sin(q(RA_BEGIN+5))*(cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)) - cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2))))) - l3_z*cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)) - cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2))) + l3_y*sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)) - cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2))) + l4_y*sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)) - cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)));
	J(0,3)= l5_z*(cos(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) - sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3))) + cos(q(RA_BEGIN+4))*cos(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) + cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))) - sin(q(RA_BEGIN+4))*sin(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) + cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))) + l3_y*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) - sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3))) + l3_z*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) + cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))) + l4_y*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) - sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3)));
	J(0,4)= l5_z*(sin(q(RA_BEGIN+6))*(cos(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) - sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3))) + sin(q(RA_BEGIN+4))*(cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)) - cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))) + cos(q(RA_BEGIN+5))*cos(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) - sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3))) - cos(q(RA_BEGIN+4))*(cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)) - cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))));
	J(0,5)= l5_z*cos(q(RA_BEGIN+6))*(cos(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) + cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))) + sin(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) - sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3))) + sin(q(RA_BEGIN+4))*(cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)) - cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))));
	J(0,6)= -l5_z*(sin(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) + cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))) - cos(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) - sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3))) + sin(q(RA_BEGIN+4))*(cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)) - cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2))))) - cos(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) - sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3))) - cos(q(RA_BEGIN+4))*(cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)) - cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))));

	J(1,0)= l3_y*(sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 + (cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2) + (cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) - l3_z*(cos(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 + (cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2) - (sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3)))/2) + l4_y*(sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 + (cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2) + (cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) + l5_z*(cos(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 + (cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2) + (cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) - cos(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 + (cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2) - (sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3)))/2) + sin(q(RA_BEGIN+4))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)))/2 - (cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2))) + sin(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 + (cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2) - (sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3)))/2) - cos(q(RA_BEGIN+4))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)))/2 - (cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2))) - (l1_z*cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN)))/2 + (l1_y*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (l2_y*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2; 
	J(1,1)= -l5_z*(cos(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2) - cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2)) + cos(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+2))*cos(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2)) - sin(q(RA_BEGIN+2))*sin(q(RA_BEGIN+4))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2))) - sin(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+2))*cos(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2)) + cos(q(RA_BEGIN+4))*sin(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2))) - l3_y*(cos(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2) - cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2)) - l3_z*(sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+2))*cos(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2)) - l4_y*(cos(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2) - cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2)) - l1_y*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2) - l1_z*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2) - l2_y*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2);
	J(1,2)= l5_z*(sin(q(RA_BEGIN+6))*(cos(q(RA_BEGIN+4))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) + cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN+4))*((cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2 + sin(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2))) + cos(q(RA_BEGIN+6))*(cos(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+4))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) - cos(q(RA_BEGIN+3))*cos(q(RA_BEGIN+4))*((cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2 + sin(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2))) + sin(q(RA_BEGIN+3))*sin(q(RA_BEGIN+5))*((cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2 + sin(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)))) - l3_z*cos(q(RA_BEGIN+3))*((cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2 + sin(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) + l3_y*sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2 + sin(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) + l4_y*sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2 + sin(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2));
	J(1,3)= l5_z*(cos(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2))) + cos(q(RA_BEGIN+4))*cos(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) - cos(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2))) - sin(q(RA_BEGIN+4))*sin(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) - cos(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2))) + l3_y*(sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2))) + l4_y*(sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2))) + l3_z*(sin(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) - cos(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2));
	J(1,4)= l5_z*(sin(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+4))*((cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2 + sin(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) + cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)))) + cos(q(RA_BEGIN+5))*cos(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2))) - cos(q(RA_BEGIN+4))*((cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2 + sin(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2))));
	J(1,5)= l5_z*cos(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+4))*((cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2 + sin(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) + cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)))) + cos(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) - cos(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2)));
	J(1,6)= l5_z*(sin(q(RA_BEGIN+6))*(cos(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+4))*((cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2 + sin(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) + cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)))) - sin(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) - cos(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2))) + cos(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2))) - cos(q(RA_BEGIN+4))*((cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2 + sin(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2))));

	J(2,0)= l3_y*(sin(q(RA_BEGIN+3))*((pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2) + (pow(3,0.5)*cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) - l5_z*(cos(q(RA_BEGIN+6))*(cos(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+3))*((pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3)))/2) + sin(q(RA_BEGIN+4))*((pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)))/2 - (pow(3,0.5)*cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)) - sin(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+3))*((pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2) + (pow(3,0.5)*cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2)) + sin(q(RA_BEGIN+6))*(cos(q(RA_BEGIN+4))*((pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)))/2 - (pow(3,0.5)*cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2) - sin(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+3))*((pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3)))/2))) - l3_z*(cos(q(RA_BEGIN+3))*((pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3)))/2) + l4_y*(sin(q(RA_BEGIN+3))*((pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2) + (pow(3,0.5)*cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*l1_z*cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN)))/2 + (pow(3,0.5)*l1_y*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*l2_y*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2;
	J(2,1)= l1_z*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) - l3_y*(cos(q(RA_BEGIN+3))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2)) - l4_y*(cos(q(RA_BEGIN+3))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2)) - l3_z*(sin(q(RA_BEGIN+3))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - cos(q(RA_BEGIN+2))*cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2)) - l1_y*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - l5_z*(cos(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+3))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2)) + cos(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - cos(q(RA_BEGIN+2))*cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2)) + sin(q(RA_BEGIN+2))*sin(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2))) - sin(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - cos(q(RA_BEGIN+2))*cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2)) - cos(q(RA_BEGIN+4))*sin(q(RA_BEGIN+2))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2))) - l2_y*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2);
	J(2,2)= l3_y*sin(q(RA_BEGIN+3))*(sin(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + (pow(3,0.5)*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2) - l3_z*cos(q(RA_BEGIN+3))*(sin(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + (pow(3,0.5)*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2) - l5_z*(cos(q(RA_BEGIN+6))*(cos(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2) + cos(q(RA_BEGIN+3))*cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + (pow(3,0.5)*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2)) - sin(q(RA_BEGIN+3))*sin(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + (pow(3,0.5)*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2)) + sin(q(RA_BEGIN+6))*(cos(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2) - cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + (pow(3,0.5)*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2))) + l4_y*sin(q(RA_BEGIN+3))*(sin(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + (pow(3,0.5)*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2);
	J(2,3)= l3_z*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) - sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)) - l3_y*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)) - l4_y*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)) - l5_z*(cos(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)) - cos(q(RA_BEGIN+4))*cos(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) - sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2))) + sin(q(RA_BEGIN+4))*sin(q(RA_BEGIN+6))*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) - sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)));
	J(2,4)= -l5_z*(sin(q(RA_BEGIN+6))*(cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)) - sin(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + (pow(3,0.5)*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2)) + cos(q(RA_BEGIN+5))*cos(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)) + cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + (pow(3,0.5)*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2)));
	J(2,5)= l5_z*cos(q(RA_BEGIN+6))*(cos(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) - sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)) - sin(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)) - sin(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + (pow(3,0.5)*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2)));
	J(2,6)= -l5_z*(sin(q(RA_BEGIN+6))*(cos(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)) - sin(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + (pow(3,0.5)*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2)) + sin(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) - sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2))) + cos(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)) + cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + (pow(3,0.5)*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2)));

	
	J(3,0)= 0.0;
	J(3,1)= cos(q(RA_BEGIN));
	J(3,2)=  sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1));
	J(3,3)= cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)) - cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2));
	J(3,4)= sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) + cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1));
	J(3,5)= cos(q(RA_BEGIN+4))*(cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)) - cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2))) - sin(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) - sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3)));
	J(3,6)= cos(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) + cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))) + sin(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) - sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3))) + sin(q(RA_BEGIN+4))*(cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)) - cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2))));

	J(4,0)=  -0.8660;
	J(4,1)= sin(q(RA_BEGIN))/2;
	J(4,2)=  - (cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2;
	J(4,3)= (cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2 + sin(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2);
	J(4,4)= sin(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) - cos(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2);
	J(4,5)=  cos(q(RA_BEGIN+4))*((cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2 + sin(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) - sin(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)));
	J(4,6)= sin(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+4))*((cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2 + sin(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) + cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)))) + cos(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) - cos(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2));

	J(5,0)= 0.5000;
	J(5,1)= (pow(3,0.5)*sin(q(RA_BEGIN)))/2;
	J(5,2)= cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2;
	J(5,3)= sin(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + (pow(3,0.5)*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2;
	J(5,4)=  cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) - sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2);
	J(5,5)= sin(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)) + cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + (pow(3,0.5)*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2);
	J(5,6)= cos(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) - sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)) - sin(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)) - sin(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + (pow(3,0.5)*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2));
}
void Robot_State_Upper::Get_Larm_Jacobian(MatrixXD& J)
{
	VectorXD q = _q;

	J.resize(6,7);
	J.setZero();

	J(0,0)= l5_z*(cos(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+3))*(sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) - cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))) - cos(q(LA_BEGIN))*cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN+1))) - cos(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+3))*(sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) - cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))) + cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3))) + sin(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)) + cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN+2))))) + sin(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+3))*(sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) - cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))) + cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3))) - cos(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)) + cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN+2))))) - l3_z*(cos(q(LA_BEGIN+3))*(sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) - cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))) + cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3))) - l4_y*(sin(q(LA_BEGIN+3))*(sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) - cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))) - cos(q(LA_BEGIN))*cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN+1))) - l3_y*(sin(q(LA_BEGIN+3))*(sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) - cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))) - cos(q(LA_BEGIN))*cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN+1))) + l1_z*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)) + l1_y*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)) + l2_y*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1));
	J(0,1)=l3_y*(cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN)) - cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3))) - l5_z*(cos(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN)) - cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3))) + cos(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+3)) + cos(q(LA_BEGIN+2))*cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))) - sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+2))*sin(q(LA_BEGIN+4)))) - sin(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+3)) + cos(q(LA_BEGIN+2))*cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))) + cos(q(LA_BEGIN+4))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+2)))) - l3_z*(cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+3)) + cos(q(LA_BEGIN+2))*cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))) + l4_y*(cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN)) - cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3))) + l1_y*cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN)) + l2_y*cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN)) - l1_z*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1));
	J(0,2)=l3_z*cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)) - cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2))) - l5_z*(sin(q(LA_BEGIN+6))*(cos(q(LA_BEGIN+4))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) + cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN+4))*(cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)) - cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))) + cos(q(LA_BEGIN+6))*(cos(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+4))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) - cos(q(LA_BEGIN+3))*cos(q(LA_BEGIN+4))*(cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)) - cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))) + sin(q(LA_BEGIN+3))*sin(q(LA_BEGIN+5))*(cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)) - cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2))))) + l3_y*sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)) - cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2))) + l4_y*sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)) - cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)));
	J(0,3)= l3_y*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) - sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3))) - l5_z*(cos(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) - sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3))) + cos(q(LA_BEGIN+4))*cos(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) + cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))) - sin(q(LA_BEGIN+4))*sin(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) + cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))) - l3_z*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) + cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))) + l4_y*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) - sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3)));
	J(0,4)= -l5_z*(sin(q(LA_BEGIN+6))*(cos(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) - sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3))) + sin(q(LA_BEGIN+4))*(cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)) - cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))) + cos(q(LA_BEGIN+5))*cos(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) - sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3))) - cos(q(LA_BEGIN+4))*(cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)) - cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))));
	J(0,5)=-l5_z*cos(q(LA_BEGIN+6))*(cos(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) + cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))) + sin(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) - sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3))) + sin(q(LA_BEGIN+4))*(cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)) - cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))));
	J(0,6)= l5_z*(sin(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) + cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))) - cos(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) - sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3))) + sin(q(LA_BEGIN+4))*(cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)) - cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2))))) - cos(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) - sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3))) - cos(q(LA_BEGIN+4))*(cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)) - cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))));

	J(1,0)= l3_y*(sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 + (cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2) + (cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) + l3_z*(cos(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 + (cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2) - (sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3)))/2) + l4_y*(sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 + (cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2) + (cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) - l5_z*(cos(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 + (cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2) + (cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) - cos(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 + (cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2) - (sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3)))/2) + sin(q(LA_BEGIN+4))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)))/2 - (cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2))) + sin(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 + (cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2) - (sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3)))/2) - cos(q(LA_BEGIN+4))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)))/2 - (cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2))) + (l1_z*cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN)))/2 + (l1_y*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 + (l2_y*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2;
	J(1,1)= l5_z*(cos(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2) - cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2)) + cos(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+2))*cos(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2)) - sin(q(LA_BEGIN+2))*sin(q(LA_BEGIN+4))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2))) - sin(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+2))*cos(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2)) + cos(q(LA_BEGIN+4))*sin(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2))) - l3_y*(cos(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2) - cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2)) + l3_z*(sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+2))*cos(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2)) - l4_y*(cos(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2) - cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2)) - l1_y*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2) + l1_z*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2) - l2_y*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2);
	J(1,2)= l3_z*cos(q(LA_BEGIN+3))*((cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2 + sin(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) - l5_z*(sin(q(LA_BEGIN+6))*(cos(q(LA_BEGIN+4))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) + cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN+4))*((cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2 + sin(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2))) + cos(q(LA_BEGIN+6))*(cos(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+4))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) - cos(q(LA_BEGIN+3))*cos(q(LA_BEGIN+4))*((cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2 + sin(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2))) + sin(q(LA_BEGIN+3))*sin(q(LA_BEGIN+5))*((cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2 + sin(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)))) + l3_y*sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2 + sin(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) + l4_y*sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2 + sin(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2));
	J(1,3)= l3_y*(sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2))) - l5_z*(cos(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2))) + cos(q(LA_BEGIN+4))*cos(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) - cos(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2))) - sin(q(LA_BEGIN+4))*sin(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) - cos(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2))) + l4_y*(sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2))) - l3_z*(sin(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) - cos(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2));
	J(1,4)= -l5_z*(sin(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+4))*((cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2 + sin(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) + cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)))) + cos(q(LA_BEGIN+5))*cos(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2))) - cos(q(LA_BEGIN+4))*((cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2 + sin(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2))));
	J(1,5)= -l5_z*cos(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+4))*((cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2 + sin(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) + cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)))) + cos(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) - cos(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2)));
	J(1,6)= -l5_z*(sin(q(LA_BEGIN+6))*(cos(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+4))*((cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2 + sin(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) + cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)))) - sin(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) - cos(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2))) + cos(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2))) - cos(q(LA_BEGIN+4))*((cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2 + sin(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2))));

	J(2,0)= - l5_z*(cos(q(LA_BEGIN+6))*(cos(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+3))*((pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 + (pow(3,0.5)*cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2) - (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3)))/2) + sin(q(LA_BEGIN+4))*((pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)) - sin(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+3))*((pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 + (pow(3,0.5)*cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2) + (pow(3,0.5)*cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2)) + sin(q(LA_BEGIN+6))*(cos(q(LA_BEGIN+4))*((pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2) - sin(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+3))*((pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 + (pow(3,0.5)*cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2) - (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3)))/2))) - l3_y*(sin(q(LA_BEGIN+3))*((pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 + (pow(3,0.5)*cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2) + (pow(3,0.5)*cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) - l3_z*(cos(q(LA_BEGIN+3))*((pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 + (pow(3,0.5)*cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2) - (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3)))/2) - l4_y*(sin(q(LA_BEGIN+3))*((pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 + (pow(3,0.5)*cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2) + (pow(3,0.5)*cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) - (pow(3,0.5)*l1_z*cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN)))/2 - (pow(3,0.5)*l1_y*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*l2_y*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2;
	J(2,1)= l5_z*(cos(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+3))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2)) + cos(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - cos(q(LA_BEGIN+2))*cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2)) + sin(q(LA_BEGIN+2))*sin(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2))) - sin(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - cos(q(LA_BEGIN+2))*cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2)) - cos(q(LA_BEGIN+4))*sin(q(LA_BEGIN+2))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2))) - l3_y*(cos(q(LA_BEGIN+3))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2)) - l4_y*(cos(q(LA_BEGIN+3))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2)) + l3_z*(sin(q(LA_BEGIN+3))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - cos(q(LA_BEGIN+2))*cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2)) - l1_y*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - l1_z*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) - l2_y*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2);
	J(2,2)= l5_z*(cos(q(LA_BEGIN+6))*(cos(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2) + cos(q(LA_BEGIN+3))*cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - (pow(3,0.5)*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2)) - sin(q(LA_BEGIN+3))*sin(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - (pow(3,0.5)*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2)) + sin(q(LA_BEGIN+6))*(cos(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2) - cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - (pow(3,0.5)*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2))) + l3_z*cos(q(LA_BEGIN+3))*(sin(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - (pow(3,0.5)*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2) + l3_y*sin(q(LA_BEGIN+3))*(sin(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - (pow(3,0.5)*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2) + l4_y*sin(q(LA_BEGIN+3))*(sin(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - (pow(3,0.5)*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2);
	J(2,3)= l5_z*(cos(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)) - cos(q(LA_BEGIN+4))*cos(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) - sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2))) + sin(q(LA_BEGIN+4))*sin(q(LA_BEGIN+6))*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) - sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2))) - l3_y*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)) - l4_y*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)) - l3_z*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) - sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2));
	J(2,4)= l5_z*(sin(q(LA_BEGIN+6))*(cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)) - sin(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - (pow(3,0.5)*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2)) + cos(q(LA_BEGIN+5))*cos(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)) + cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - (pow(3,0.5)*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2)));
	J(2,5)= -l5_z*cos(q(LA_BEGIN+6))*(cos(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) - sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)) - sin(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)) - sin(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - (pow(3,0.5)*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2)));
	J(2,6)= l5_z*(sin(q(LA_BEGIN+6))*(cos(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)) - sin(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - (pow(3,0.5)*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2)) + sin(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) - sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2))) + cos(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)) + cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - (pow(3,0.5)*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2)));

	J(3,0)= 0;
	J(4,0)= 0.8660;
	J(5,0)= 0.5; 

	J(3,1)= cos(q(LA_BEGIN));
	J(4,1)= sin(q(LA_BEGIN))/2;
	J(5,1)= -(pow(3,0.5)*sin(q(LA_BEGIN)))/2;

	J(3,2)= sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1));
	J(4,2)=  (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2 - (cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2;
	J(5,2)= cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2;

	J(3,3)=  cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)) - cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2));
	J(4,3)= (cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2 + sin(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2);
	J(5,3)= sin(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - (pow(3,0.5)*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2;

	J(3,4)= sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) + cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1));
	J(4,4)= sin(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) - cos(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2);
	J(5,4)= cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) - sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2);

	J(3,5)= cos(q(LA_BEGIN+4))*(cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)) - cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2))) - sin(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) - sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3)));
	J(4,5)= cos(q(LA_BEGIN+4))*((cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2 + sin(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) - sin(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)));
	J(5,5)= sin(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)) + cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - (pow(3,0.5)*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2);

	J(3,6)= cos(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) + cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))) + sin(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) - sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3))) + sin(q(LA_BEGIN+4))*(cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)) - cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2))));
	J(4,6)= sin(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+4))*((cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2 + sin(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) + cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)))) + cos(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) - cos(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2));
	J(5,6)= cos(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) - sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)) - sin(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)) - sin(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - (pow(3,0.5)*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2));

}
void Robot_State_Upper::Get_T_Rarm(HTransform& T)
{
	Vector3D r_temp;
	r_temp.setZero();
	Matrix3D R_R;
	VectorXD q = _q;

	R_R(0,0)= sin(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) + cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))) - cos(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) - sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3))) + sin(q(RA_BEGIN+4))*(cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)) - cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2))))) - cos(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) - sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3))) - cos(q(RA_BEGIN+4))*(cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)) - cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2))));
	R_R(0,1)=- cos(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) + cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))) - sin(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) - sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3))) + sin(q(RA_BEGIN+4))*(cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)) - cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2))));
	R_R(0,2)=cos(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) + cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))) - cos(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) - sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3))) + sin(q(RA_BEGIN+4))*(cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)) - cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2))))) + sin(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) - sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3))) - cos(q(RA_BEGIN+4))*(cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)) - cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2))));

	R_R(1,0)= - sin(q(RA_BEGIN+6))*(cos(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+4))*((cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2 + sin(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) + cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)))) - sin(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) - cos(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2))) - cos(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2))) - cos(q(RA_BEGIN+4))*((cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2 + sin(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)));
	R_R(1,1)=- sin(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+4))*((cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2 + sin(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) + cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)))) - cos(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) - cos(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2));
	R_R(1,2)=sin(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2))) - cos(q(RA_BEGIN+4))*((cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2 + sin(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2))) - cos(q(RA_BEGIN+6))*(cos(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+4))*((cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2 + sin(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) + cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)))) - sin(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) - cos(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2)));

	R_R(2,0)=sin(q(RA_BEGIN+6))*(cos(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)) - sin(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + (pow(3,0.5)*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2)) + sin(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) - sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2))) + cos(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)) + cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + (pow(3,0.5)*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2));
	R_R(2,1)=sin(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)) - sin(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + (pow(3,0.5)*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2)) - cos(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) - sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2));
	R_R(2,2)=cos(q(RA_BEGIN+6))*(cos(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)) - sin(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + (pow(3,0.5)*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2)) + sin(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) - sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2))) - sin(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)) + cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + (pow(3,0.5)*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2));

	r_temp(0) = l3_y*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) + cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))) + l4_y*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) + cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))) - l3_z*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) - sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3))) + l5_z*(cos(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) + cos(q(RA_BEGIN+3))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))) - cos(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) - sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3))) + sin(q(RA_BEGIN+4))*(cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)) - cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2))))) + sin(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+4))*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN))*sin(q(RA_BEGIN+2)) + cos(q(RA_BEGIN+1))*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN))) - sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1))*sin(q(RA_BEGIN+3))) - cos(q(RA_BEGIN+4))*(cos(q(RA_BEGIN))*cos(q(RA_BEGIN+2)) - cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2))))) - l1_z*cos(q(RA_BEGIN+1))*sin(q(RA_BEGIN)) + l1_y*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1)) + l2_y*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+1));
	r_temp(1) = l3_y*(sin(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) - cos(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2)) - l0_y - l3_z*(sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2))) + l4_y*(sin(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) - cos(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2)) + l5_z*(sin(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2))) - cos(q(RA_BEGIN+4))*((cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2 + sin(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2))) - cos(q(RA_BEGIN+6))*(cos(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+4))*((cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2 + sin(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) + cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)))) - sin(q(RA_BEGIN+5))*(sin(q(RA_BEGIN+3))*((sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2 - cos(q(RA_BEGIN+2))*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2)) - cos(q(RA_BEGIN+3))*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2)))) - l1_y*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2) + l1_z*((cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2 - (pow(3,0.5)*sin(q(RA_BEGIN+1)))/2) - l2_y*((cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2 + (pow(3,0.5)*cos(q(RA_BEGIN+1)))/2);
	r_temp(2) = l0_z + l5_z*(cos(q(RA_BEGIN+6))*(cos(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)) - sin(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + (pow(3,0.5)*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2)) + sin(q(RA_BEGIN+5))*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) - sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2))) - sin(q(RA_BEGIN+6))*(sin(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)) + cos(q(RA_BEGIN+4))*(sin(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + (pow(3,0.5)*cos(q(RA_BEGIN+2))*sin(q(RA_BEGIN)))/2))) + l3_y*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) - sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)) + l3_z*(sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) + cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)) + l4_y*(cos(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) - sin(q(RA_BEGIN+3))*(cos(q(RA_BEGIN+2))*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) - (pow(3,0.5)*sin(q(RA_BEGIN))*sin(q(RA_BEGIN+2)))/2)) + l1_y*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2) + l1_z*(sin(q(RA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(RA_BEGIN))*cos(q(RA_BEGIN+1)))/2) + l2_y*(cos(q(RA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(RA_BEGIN))*sin(q(RA_BEGIN+1)))/2);
		
	T.linear() = R_R;
	T.translation() =r_temp;
}
void Robot_State_Upper::Get_T_Larm(HTransform& T)
{
	Vector3D r_temp;
	r_temp.setZero();
	Matrix3D R_R;
	VectorXD q = _q;

	R_R(0,0)= sin(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) + cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))) - cos(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) - sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3))) + sin(q(LA_BEGIN+4))*(cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)) - cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2))))) - cos(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) - sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3))) - cos(q(LA_BEGIN+4))*(cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)) - cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2))));
	R_R(0,1)= cos(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) + cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))) + sin(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) - sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3))) + sin(q(LA_BEGIN+4))*(cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)) - cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2))));
	R_R(0,2)= sin(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) + cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))) - cos(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) - sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3))) + sin(q(LA_BEGIN+4))*(cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)) - cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2))))) - cos(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) - sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3))) - cos(q(LA_BEGIN+4))*(cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)) - cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2))));

	R_R(1,0)=  - sin(q(LA_BEGIN+6))*(cos(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+4))*((cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2 + sin(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) + cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)))) - sin(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) - cos(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2))) - cos(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2))) - cos(q(LA_BEGIN+4))*((cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2 + sin(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)));
	R_R(1,1)=  sin(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+4))*((cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2 + sin(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) + cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)))) + cos(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) - cos(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2));
	R_R(1,2)=cos(q(LA_BEGIN+6))*(cos(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+4))*((cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2 + sin(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) + cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)))) - sin(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) - cos(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2))) - sin(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2))) - cos(q(LA_BEGIN+4))*((cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2 + sin(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)));

	R_R(2,0)=sin(q(LA_BEGIN+6))*(cos(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)) - sin(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - (pow(3,0.5)*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2)) + sin(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) - sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2))) + cos(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)) + cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - (pow(3,0.5)*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2));
	R_R(2,1)=cos(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) - sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)) - sin(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)) - sin(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - (pow(3,0.5)*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2));
	R_R(2,2)=sin(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)) + cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - (pow(3,0.5)*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2)) - cos(q(LA_BEGIN+6))*(cos(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)) - sin(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - (pow(3,0.5)*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2)) + sin(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) - sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)));

	r_temp(0) = l3_y*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) + cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))) + l4_y*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) + cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))) + l3_z*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) - sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3))) - l5_z*(cos(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) + cos(q(LA_BEGIN+3))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))) - cos(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) - sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3))) + sin(q(LA_BEGIN+4))*(cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)) - cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2))))) + sin(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+4))*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN))*sin(q(LA_BEGIN+2)) + cos(q(LA_BEGIN+1))*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN))) - sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1))*sin(q(LA_BEGIN+3))) - cos(q(LA_BEGIN+4))*(cos(q(LA_BEGIN))*cos(q(LA_BEGIN+2)) - cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2))))) + l1_z*cos(q(LA_BEGIN+1))*sin(q(LA_BEGIN)) + l1_y*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1)) + l2_y*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+1));
	r_temp(1) =  l0_y + l3_y*(sin(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) - cos(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2)) + l3_z*(sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2))) + l4_y*(sin(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) - cos(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2)) - l5_z*(sin(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2))) - cos(q(LA_BEGIN+4))*((cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2 + sin(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2))) - cos(q(LA_BEGIN+6))*(cos(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+4))*((cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2 + sin(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) + cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)))) - sin(q(LA_BEGIN+5))*(sin(q(LA_BEGIN+3))*((sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2 - cos(q(LA_BEGIN+2))*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2)) - cos(q(LA_BEGIN+3))*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2)))) - l1_y*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2) - l1_z*((cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2 + (pow(3,0.5)*sin(q(LA_BEGIN+1)))/2) - l2_y*((cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2 - (pow(3,0.5)*cos(q(LA_BEGIN+1)))/2);
	r_temp(2) = l0_z - l5_z*(cos(q(LA_BEGIN+6))*(cos(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)) - sin(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - (pow(3,0.5)*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2)) + sin(q(LA_BEGIN+5))*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) - sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2))) - sin(q(LA_BEGIN+6))*(sin(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)) + cos(q(LA_BEGIN+4))*(sin(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) - (pow(3,0.5)*cos(q(LA_BEGIN+2))*sin(q(LA_BEGIN)))/2))) + l3_y*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) - sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)) - l3_z*(sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) + cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)) + l4_y*(cos(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) - sin(q(LA_BEGIN+3))*(cos(q(LA_BEGIN+2))*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + (pow(3,0.5)*sin(q(LA_BEGIN))*sin(q(LA_BEGIN+2)))/2)) + l1_y*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2) - l1_z*(sin(q(LA_BEGIN+1))/2 - (pow(3,0.5)*cos(q(LA_BEGIN))*cos(q(LA_BEGIN+1)))/2) + l2_y*(cos(q(LA_BEGIN+1))/2 + (pow(3,0.5)*cos(q(LA_BEGIN))*sin(q(LA_BEGIN+1)))/2);

	T.linear() = R_R;
	T.translation() =r_temp;
}
void Robot_State_Upper::Get_Rarm_angle(Vector3D& angle)
{
	Rot2euler(_Rarm.T.linear(), angle);
}
void Robot_State_Upper::Get_Larm_angle(Vector3D& angle)
{
	Rot2euler(_Larm.T.linear(), angle);
}
